#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaData.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Diplomas")]
	public partial class DiplomasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public DiplomasDataContext() : 
				base(global::DiplomaData.Properties.Settings.Default.DiplomasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DiplomasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiplomasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiplomasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiplomasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Commission_rus> Commission_rus
		{
			get
			{
				return this.GetTable<Commission_rus>();
			}
		}
		
		public System.Data.Linq.Table<Diplom_rus> Diplom_rus
		{
			get
			{
				return this.GetTable<Diplom_rus>();
			}
		}
		
		public System.Data.Linq.Table<Form_of_education_rus> Form_of_education_rus
		{
			get
			{
				return this.GetTable<Form_of_education_rus>();
			}
		}
		
		public System.Data.Linq.Table<Group_rus> Group_rus
		{
			get
			{
				return this.GetTable<Group_rus>();
			}
		}
		
		public System.Data.Linq.Table<Lecturer_rus> Lecturer_rus
		{
			get
			{
				return this.GetTable<Lecturer_rus>();
			}
		}
		
		public System.Data.Linq.Table<Reviewer_rus> Reviewer_rus
		{
			get
			{
				return this.GetTable<Reviewer_rus>();
			}
		}
		
		public System.Data.Linq.Table<Specialty_rus> Specialty_rus
		{
			get
			{
				return this.GetTable<Specialty_rus>();
			}
		}
		
		public System.Data.Linq.Table<Thesis_rus> Thesis_rus
		{
			get
			{
				return this.GetTable<Thesis_rus>();
			}
		}
		
		public System.Data.Linq.Table<Student_rus> Student_rus
		{
			get
			{
				return this.GetTable<Student_rus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Commission_rus")]
	public partial class Commission_rus
	{
		
		private int _id;
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		public Commission_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(50)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Diplom_rus")]
	public partial class Diplom_rus
	{
		
		private int _id;
		
		private int _Тема;
		
		private int _Студент;
		
		private System.DateTime _Дата_сдачи;
		
		private int _Руководитель;
		
		private int _Файлы;
		
		private int _Пояснительная_записка;
		
		public Diplom_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Тема", DbType="Int NOT NULL")]
		public int Тема
		{
			get
			{
				return this._Тема;
			}
			set
			{
				if ((this._Тема != value))
				{
					this._Тема = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Студент", DbType="Int NOT NULL")]
		public int Студент
		{
			get
			{
				return this._Студент;
			}
			set
			{
				if ((this._Студент != value))
				{
					this._Студент = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата сдачи]", Storage="_Дата_сдачи", DbType="Date NOT NULL")]
		public System.DateTime Дата_сдачи
		{
			get
			{
				return this._Дата_сдачи;
			}
			set
			{
				if ((this._Дата_сдачи != value))
				{
					this._Дата_сдачи = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Руководитель", DbType="Int NOT NULL")]
		public int Руководитель
		{
			get
			{
				return this._Руководитель;
			}
			set
			{
				if ((this._Руководитель != value))
				{
					this._Руководитель = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Файлы", DbType="Int NOT NULL")]
		public int Файлы
		{
			get
			{
				return this._Файлы;
			}
			set
			{
				if ((this._Файлы != value))
				{
					this._Файлы = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Пояснительная записка]", Storage="_Пояснительная_записка", DbType="Int NOT NULL")]
		public int Пояснительная_записка
		{
			get
			{
				return this._Пояснительная_записка;
			}
			set
			{
				if ((this._Пояснительная_записка != value))
				{
					this._Пояснительная_записка = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Form_of_education_rus")]
	public partial class Form_of_education_rus
	{
		
		private string _Форма_обучения;
		
		private short _id;
		
		public Form_of_education_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Форма обучения]", Storage="_Форма_обучения", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Форма_обучения
		{
			get
			{
				return this._Форма_обучения;
			}
			set
			{
				if ((this._Форма_обучения != value))
				{
					this._Форма_обучения = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="SmallInt NOT NULL")]
		public short id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Group_rus")]
	public partial class Group_rus
	{
		
		private string _Номер_группы;
		
		private string _Специальность;
		
		private int _Куратор;
		
		private System.Nullable<short> _Форма_обучения;
		
		public Group_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер группы]", Storage="_Номер_группы", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string Номер_группы
		{
			get
			{
				return this._Номер_группы;
			}
			set
			{
				if ((this._Номер_группы != value))
				{
					this._Номер_группы = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Специальность", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string Специальность
		{
			get
			{
				return this._Специальность;
			}
			set
			{
				if ((this._Специальность != value))
				{
					this._Специальность = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Куратор", DbType="Int NOT NULL")]
		public int Куратор
		{
			get
			{
				return this._Куратор;
			}
			set
			{
				if ((this._Куратор != value))
				{
					this._Куратор = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Форма обучения]", Storage="_Форма_обучения", DbType="SmallInt")]
		public System.Nullable<short> Форма_обучения
		{
			get
			{
				return this._Форма_обучения;
			}
			set
			{
				if ((this._Форма_обучения != value))
				{
					this._Форма_обучения = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lecturer_rus")]
	public partial class Lecturer_rus
	{
		
		private int _id;
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		public Lecturer_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(50)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reviewer_rus")]
	public partial class Reviewer_rus
	{
		
		private int _id;
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private string _Компания;
		
		public Reviewer_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(50)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Компания", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Компания
		{
			get
			{
				return this._Компания;
			}
			set
			{
				if ((this._Компания != value))
				{
					this._Компания = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Specialty_rus")]
	public partial class Specialty_rus
	{
		
		private string _Шифр_специальности;
		
		private string _Специальность;
		
		public Specialty_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Шифр специальности]", Storage="_Шифр_специальности", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string Шифр_специальности
		{
			get
			{
				return this._Шифр_специальности;
			}
			set
			{
				if ((this._Шифр_специальности != value))
				{
					this._Шифр_специальности = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Специальность", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Специальность
		{
			get
			{
				return this._Специальность;
			}
			set
			{
				if ((this._Специальность != value))
				{
					this._Специальность = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thesis_rus")]
	public partial class Thesis_rus
	{
		
		private int _id;
		
		private string _Название_темы;
		
		private string _Описание;
		
		private System.DateTime _Дата_выдачи;
		
		private bool _Занята__не_занята;
		
		public Thesis_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Название темы]", Storage="_Название_темы", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Название_темы
		{
			get
			{
				return this._Название_темы;
			}
			set
			{
				if ((this._Название_темы != value))
				{
					this._Название_темы = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Описание", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Описание
		{
			get
			{
				return this._Описание;
			}
			set
			{
				if ((this._Описание != value))
				{
					this._Описание = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата выдачи]", Storage="_Дата_выдачи", DbType="Date NOT NULL")]
		public System.DateTime Дата_выдачи
		{
			get
			{
				return this._Дата_выдачи;
			}
			set
			{
				if ((this._Дата_выдачи != value))
				{
					this._Дата_выдачи = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Занята/ не занята]", Storage="_Занята__не_занята", DbType="Bit NOT NULL")]
		public bool Занята__не_занята
		{
			get
			{
				return this._Занята__не_занята;
			}
			set
			{
				if ((this._Занята__не_занята != value))
				{
					this._Занята__не_занята = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student_rus")]
	public partial class Student_rus
	{
		
		private int _id;
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private string _Номер_группы;
		
		public Student_rus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(50)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Номер_группы", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string Номер_группы
		{
			get
			{
				return this._Номер_группы;
			}
			set
			{
				if ((this._Номер_группы != value))
				{
					this._Номер_группы = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
