<?xml version="1.0" encoding="utf-8"?><Database Name="Diplomas" Class="DiplomaDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Diplomas;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="DiplomaData.Properties.Settings" SettingsPropertyName="DiplomasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Commission" Member="Commission">
    <Type Name="Commission">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="patronymic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Commission_Commission_Specialty" Member="Commission_Specialty" ThisKey="id" OtherKey="Commission" Type="Commission_Specialty" />
    </Type>
  </Table>
  <Table Name="dbo.Commission_Specialty" Member="Commission_Specialty">
    <Type Name="Commission_Specialty">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Commission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Specialty" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="Commission_Commission_Specialty" Member="Commission1" ThisKey="Commission" OtherKey="id" Type="Commission" IsForeignKey="true" />
      <Association Name="Specialty_Commission_Specialty" Member="Specialty1" ThisKey="Specialty" OtherKey="cipher" Type="Specialty" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Criteria" Member="Criteria">
    <Type Name="Criteria">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataFile" Member="DataFile">
    <Type Name="DataFile">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DataFile_Diploma" Member="Diploma" ThisKey="id" OtherKey="Data" Type="Diploma" />
      <Association Name="DataFile_Diploma1" Member="Diploma1" ThisKey="id" OtherKey="Explanatory_note" Type="Diploma" />
    </Type>
  </Table>
  <Table Name="dbo.Diploma" Member="Diploma">
    <Type Name="Diploma">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Thesis" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Student" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Lecturer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Explanatory_note" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Diploma_Diploma_Reviewer" Member="Diploma_Reviewer" ThisKey="id" OtherKey="Diploma" Type="Diploma_Reviewer" />
      <Association Name="DataFile_Diploma" Member="DataFile" ThisKey="Data" OtherKey="id" Type="DataFile" IsForeignKey="true" />
      <Association Name="DataFile_Diploma1" Member="DataFile1" ThisKey="Explanatory_note" OtherKey="id" Type="DataFile" IsForeignKey="true" />
      <Association Name="Lecturer_Diploma" Member="Lecturer1" ThisKey="Lecturer" OtherKey="id" Type="Lecturer" IsForeignKey="true" />
      <Association Name="Student_Diploma" Member="Student1" ThisKey="Student" OtherKey="id" Type="Student" IsForeignKey="true" />
      <Association Name="Thesis_Diploma" Member="Thesis1" ThisKey="Thesis" OtherKey="id" Type="Thesis" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Diploma_Reviewer" Member="Diploma_Reviewer">
    <Type Name="Diploma_Reviewer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Reviewer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Diploma" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Diploma_Diploma_Reviewer" Member="Diploma1" ThisKey="Diploma" OtherKey="id" Type="Diploma" IsForeignKey="true" />
      <Association Name="Reviewer_Diploma_Reviewer" Member="Reviewer1" ThisKey="Reviewer" OtherKey="id" Type="Reviewer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Form of education]" Member="Form_of_education">
    <Type Name="Form_of_education">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Form_of_education_Group" Member="Group" ThisKey="id" OtherKey="form_of_education" Type="Group" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Group">
    <Type Name="Group">
      <Column Name="number" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Specialty" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="Curator" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[form of education]" Member="form_of_education" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Group_Student" Member="Student" ThisKey="number" OtherKey="Group_number" Type="Student" />
      <Association Name="Form_of_education_Group" Member="Form_of_education1" ThisKey="form_of_education" OtherKey="id" Type="Form_of_education" IsForeignKey="true" />
      <Association Name="Lecturer_Group" Member="Lecturer" ThisKey="Curator" OtherKey="id" Type="Lecturer" IsForeignKey="true" />
      <Association Name="Specialty_Group" Member="Specialty1" ThisKey="Specialty" OtherKey="cipher" Type="Specialty" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lecturer" Member="Lecturer">
    <Type Name="Lecturer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="patronymic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Lecturer_Diploma" Member="Diploma" ThisKey="id" OtherKey="Lecturer" Type="Diploma" />
      <Association Name="Lecturer_Group" Member="Group" ThisKey="id" OtherKey="Curator" Type="Group" />
    </Type>
  </Table>
  <Table Name="dbo.Mark" Member="Mark">
    <Type Name="Mark">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mark" Member="mark1" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Questions">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reviewer" Member="Reviewer">
    <Type Name="Reviewer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="patronymic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="company" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Reviewer_Diploma_Reviewer" Member="Diploma_Reviewer" ThisKey="id" OtherKey="Reviewer" Type="Diploma_Reviewer" />
    </Type>
  </Table>
  <Table Name="dbo.Specialty" Member="Specialty">
    <Type Name="Specialty">
      <Column Name="cipher" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Specialty_Commission_Specialty" Member="Commission_Specialty" ThisKey="cipher" OtherKey="Specialty" Type="Commission_Specialty" />
      <Association Name="Specialty_Group" Member="Group" ThisKey="cipher" OtherKey="Specialty" Type="Group" />
      <Association Name="Specialty_Specialty_Thesis" Member="Specialty_Thesis" ThisKey="cipher" OtherKey="Specialty" Type="Specialty_Thesis" />
    </Type>
  </Table>
  <Table Name="dbo.Specialty_Thesis" Member="Specialty_Thesis">
    <Type Name="Specialty_Thesis">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Specialty" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="Thesis" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Specialty_Specialty_Thesis" Member="Specialty1" ThisKey="Specialty" OtherKey="cipher" Type="Specialty" IsForeignKey="true" />
      <Association Name="Thesis_Specialty_Thesis" Member="Thesis1" ThisKey="Thesis" OtherKey="id" Type="Thesis" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Student">
    <Type Name="Student">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="patronymic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Group_number" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Student_Diploma" Member="Diploma" ThisKey="id" OtherKey="Student" Type="Diploma" />
      <Association Name="Group_Student" Member="Group" ThisKey="Group_number" OtherKey="number" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Thesis" Member="Thesis">
    <Type Name="Thesis">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="used" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="remotely" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Thesis_Diploma" Member="Diploma" ThisKey="id" OtherKey="Thesis" Type="Diploma" />
      <Association Name="Thesis_Specialty_Thesis" Member="Specialty_Thesis" ThisKey="id" OtherKey="Thesis" Type="Specialty_Thesis" />
    </Type>
  </Table>
</Database>